import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { ButtonLink } from "@/components/button-link";
import { DetailDialog } from "@/components/detail-dialog";
import { PageHero } from "@/components/page-hero";
import { serviceCatalog } from "@/lib/service-catalog";

export const metadata: Metadata = {
  title: "Concepts & cas d’usage",
  description: "Explorez des idées de solutions NEURALIS en web, applications, data et IA. Les photographies illustrent des usages possibles et ne présentent pas des projets clients.",
  alternates: { canonical: "/portfolio" },
};

const concepts = [
  { title: "Une vitrine qui ouvre la conversation", category: "Site web", image: "sites-web", alt: "Illustration conceptuelle d’une expérience web professionnelle", summary: "Présenter une entreprise et guider le visiteur vers une demande qualifiée.", problem: "Une activité peut être difficile à comprendre lorsque ses offres, ses coordonnées et ses contenus sont dispersés.", journey: ["Découvrir l’activité et sa proposition de valeur.", "Explorer les services et les réponses aux questions fréquentes.", "Prendre contact avec un besoin déjà mieux formulé."], possibilities: ["Site vitrine responsive", "Pages services", "Formulaire de contact", "Gestion de contenus"], caution: "Les textes, l’identité et les fonctionnalités seraient conçus pour l’organisation concernée." },
  { title: "L’activité à portée de main", category: "Application", image: "applications", alt: "Illustration conceptuelle d’applications sur plusieurs écrans", summary: "Un espace mobile pour consulter, saisir et suivre les informations du quotidien.", problem: "Les équipes peuvent perdre du temps à rechercher une information ou à ressaisir les mêmes données dans plusieurs outils.", journey: ["Se connecter avec un profil et des droits adaptés.", "Consulter les tâches ou les dossiers utiles à son rôle.", "Enregistrer une action et suivre son avancement."], possibilities: ["Application web ou mobile", "Espace utilisateur", "Saisie structurée", "Notifications à définir"], caution: "Les usages hors connexion, les notifications et les intégrations nécessitent un cadrage spécifique." },
  { title: "Un campus numérique mieux organisé", category: "Plateforme métier", image: "plateformes", alt: "Illustration conceptuelle d’une plateforme numérique de gestion", summary: "Relier ressources pédagogiques, inscriptions et suivi des apprenants.", problem: "Dans un organisme de formation, la multiplication des supports rend le suivi pédagogique et administratif plus complexe.", journey: ["L’administration prépare les profils et les inscriptions.", "Les formateurs publient les ressources et les activités.", "Les apprenants accèdent à leur parcours et consultent leur progression."], possibilities: ["Espace de formation", "Gestion des rôles", "Ressources et évaluations", "Suivi pédagogique"], caution: "La gestion de données personnelles, les accès et la conservation des dossiers sont définis avant développement." },
  { title: "Des données qui éclairent les décisions", category: "Data & pilotage", image: "data", alt: "Photographie d’un travail d’analyse de données sur ordinateur", summary: "Rassembler les indicateurs essentiels dans une vue de pilotage lisible.", problem: "Des chiffres répartis dans plusieurs fichiers peuvent être difficiles à comparer et à actualiser correctement.", journey: ["Identifier les sources disponibles et vérifier leur qualité.", "Définir les indicateurs avec les personnes qui les utilisent.", "Explorer les tendances et retrouver les données de référence."], possibilities: ["Tableau de bord", "Filtres par période", "Exports", "Mise à jour à définir"], caution: "La scène photographiée ne présente aucune donnée ni performance d’un client NEURALIS." },
  { title: "Un assistant pour les questions récurrentes", category: "IA & automatisation", image: "ia", alt: "Illustration conceptuelle de connexions et d’assistance par intelligence artificielle", summary: "Explorer l’assistance documentaire avec des sources définies et des limites visibles.", problem: "Retrouver une procédure ou répondre plusieurs fois à la même question mobilise du temps et de l’attention.", journey: ["Délimiter un corpus documentaire autorisé.", "Poser une question et obtenir une réponse à vérifier.", "Retrouver la source ou transmettre à une personne en cas d’incertitude."], possibilities: ["Recherche documentaire", "Aide à la rédaction", "Réponses avec sources", "Escalade humaine"], caution: "Un système d’IA peut se tromper. Confidentialité, évaluation des réponses et validation humaine font partie du cadrage." },
  { title: "Une marque cohérente, partout", category: "Communication", image: "communication", alt: "Photographe réalisant une prise de vue pour un contenu de communication", summary: "Donner une même direction aux messages, aux visuels et aux canaux de contact.", problem: "Des publications sans ligne directrice peuvent rendre une marque moins reconnaissable et son offre moins lisible.", journey: ["Clarifier les publics, le ton et les messages prioritaires.", "Décliner une direction visuelle sur les supports utiles.", "Organiser les contenus et observer les retours disponibles."], possibilities: ["Identité visuelle", "Supports sociaux", "Calendrier éditorial", "Profils professionnels"], caution: "Cette photographie illustre un travail créatif ; elle ne présente pas une campagne client NEURALIS." },
];

function photoAlt(concept: (typeof concepts)[number]) {
  return serviceCatalog.find(service => service.id === concept.image)?.imageAlt ?? concept.alt;
}

export default function PortfolioPage() {
  return <>
    <PageHero eyebrow="Concepts & cas d’usage" title="Imaginez le projet qui vous sera utile." description="Six situations concrètes pour visualiser ce qu’un site, une application ou un outil métier peut changer au quotidien. Ce sont des pistes de réflexion, pas des réalisations clients." secondaryLabel="Explorer la galerie" secondaryHref="#galerie" />
    <section id="galerie" className="studio-section scroll-mt-28"><div className="studio-container">
      <div className="mb-10 rounded-2xl border border-cyan-200 bg-cyan-50 p-5 text-sm leading-7 text-slate-700"><span className="font-semibold text-[#0F172A]">Une galerie d’inspiration, en toute transparence.</span> Ces photographies illustrent des situations de travail et des usages possibles. Les personnes photographiées ne sont pas présentées comme notre équipe ou nos clients ; ces images ne montrent pas des projets livrés.</div>
      <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
        {concepts.map(concept => <article key={concept.title} className="studio-panel group flex flex-col overflow-hidden transition-[transform,box-shadow] duration-300 motion-safe:hover:-translate-y-1 motion-safe:hover:shadow-[0_24px_56px_rgba(15,23,42,0.12)] motion-reduce:transition-none">
          <div className="relative overflow-hidden border-b border-slate-200"><Image src={"/images/services/" + concept.image + ".webp"} alt={photoAlt(concept)} width={1200} height={800} sizes="(min-width: 1024px) 33vw, (min-width: 768px) 50vw, 100vw" className="aspect-[3/2] w-full object-cover transition-transform duration-500 motion-safe:group-hover:scale-105 motion-reduce:transition-none" /><span className="absolute bottom-3 left-3 rounded-full border border-white/80 bg-white/95 px-3 py-1.5 text-[11px] font-semibold text-[#0F172A] shadow-sm">Cas d’usage illustré</span></div>
          <div className="flex flex-1 flex-col p-6"><p className="studio-kicker">{concept.category}</p><h2 className="mt-3 text-xl font-semibold leading-7 text-[#0F172A]">{concept.title}</h2><p className="mt-3 text-sm leading-7 text-slate-600">{concept.summary}</p>
            <div className="mt-auto pt-6"><DetailDialog title={concept.title} eyebrow={concept.category + " · Concept illustratif"} triggerLabel="Explorer le cas d’usage" triggerClassName="inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#0F172A] px-5 py-3 text-sm font-semibold text-white shadow-sm transition-colors duration-200 hover:bg-[#075d72] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-cyan-700 motion-reduce:transition-none">
              <Image src={"/images/services/" + concept.image + ".webp"} alt={photoAlt(concept)} width={1200} height={800} sizes="(min-width: 1024px) 800px, 100vw" className="aspect-[3/2] w-full rounded-2xl object-cover" />
              <p className="mt-3 text-xs leading-6 text-slate-600">Photographie d’illustration — aucun projet ou client présenté.</p>
              <h3 className="mt-8 text-xl font-semibold text-[#0F172A]">Le problème à explorer</h3><p className="mt-3 leading-8 text-slate-700">{concept.problem}</p>
              <h3 className="mt-7 text-xl font-semibold text-[#0F172A]">Un parcours possible</h3><ol className="mt-4 grid gap-3 sm:grid-cols-3">{concept.journey.map((step,index) => <li className="flex gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm leading-6 text-slate-700" key={step}><span className="font-bold text-cyan-800">0{index + 1}</span>{step}</li>)}</ol>
              <h3 className="mt-7 text-xl font-semibold text-[#0F172A]">Fonctionnalités envisageables</h3><div className="studio-tags mt-4">{concept.possibilities.map(item => <span key={item}>{item}</span>)}</div>
              <p className="mt-7 rounded-2xl border border-cyan-200 bg-cyan-50 p-5 text-sm leading-7 text-slate-700">{concept.caution}</p><div className="mt-8 flex flex-wrap items-center gap-5"><ButtonLink href="/contact">Discuter d’un projet similaire</ButtonLink><Link href={"/services/" + concept.image} className="studio-link">Voir l’expertise <ArrowUpRight className="h-4 w-4" aria-hidden /></Link></div>
            </DetailDialog></div>
          </div>
        </article>)}
      </div>
    </div></section>
    <section className="studio-section studio-section-alt border-t border-slate-200"><div className="studio-container max-w-4xl text-center"><p className="studio-kicker">Votre contexte change tout</p><h2 className="studio-heading mt-3">L’inspiration est ici. Le projet commence avec vous.</h2><p className="studio-copy mx-auto mt-5 max-w-2xl">Ces concepts ouvrent la discussion. Votre solution se construit à partir de vos utilisateurs, de vos contraintes et d’un périmètre validé.</p><div className="mt-8"><ButtonLink href="/contact">Parler de mon idée</ButtonLink></div></div></section>
  </>;
}
